using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Game.Enums
{
	[System.Serializable]
	public enum Gender { MALE, FEMALE, ANY };
	public enum MapCategory { TERRAIN, RAINFALL, FERTILITY, BIOME };
	public enum LandType { OCEAN, FLAT, HILLS, MOUNTAINS };
	public enum PriorityType { MILITARY, INFRASTRUCTURE, MERCANTILE, POLITICAL, RELIGIOUS};
	public enum TroopType { LIGHT_INFANTRY, HEAVY_INFANTRY, LIGHT_CAVALRY, HEAVY_CAVALRY, ARCHER};
	public enum StatType { STRENGTH, DEXTERITY, CONSTITUTION, INTELLIGENCE, WISDOM, CHARISMA, LUCK };
	public enum RoleType { GOVERNER, MAGIC_USER, ROGUE };
	public enum CreatureSize { TINY, SMALL, MEDIUM, LARGE, HUGE, GARGANTUAN};
	public enum CreatureType { ABERRATION, BEAST, CELESTIAL, CONSTRUCT, DRAGON, ELEMENTAL, FEY, FIEND, GIANT, HUMANOID, MONSTROSITY, OOZE, PLANT, UNDEAD };
	public enum DamageType { SLASHING, PIERCING, BLUDGEONING, POISON, ACID, FIRE, COLD, RADIANT, NECROTIC, LIGHTNING, THUNDER, FORCE, PSYCHIC, NONMAGICAL };
	public enum ConditionType { BLINDED, CHARMED, DEAFENED, FRIGHTENED, GRAPPLED, INCAPACITATED, INVISIBLE, PARALYZED, PETRIFIED, POISONED, PRONE, RESTRAINED, STUNNED, UNCONSCIOUS, EXHAUSTION };
	public enum CreatureAlignment { LAWFUL_GOOD, LAWFUL_NEUTRAL, LAWFUL_EVIL, NEUTRAL_GOOD, TRUE_NEUTRAL, NEUTRAL_EVIL, CHAOTIC_GOOD, CHAOTIC_NEUTRAL, CHAOTIC_EVIL, UNALIGNED, ANY_ALIGNMENT, ANY_GOOD_ALIGNMENT, ANY_EVIL_ALIGNMENT, ANY_LAWFUL_ALIGNMENT, ANY_CHAOTIC_ALIGNMENT };
	public enum CoinType { CP, SP, GP, PP};
	public enum WeaponCategory { SIMPLE_MELEE, SIMPLE_RANGED, MARTIAL_MELEE, MARTIAL_RANGED };
	public enum ArmorCategory { LIGHT, MEDIUM, HEAVY, SHIELD };
	public enum ItemGrade { AWFUL, POOR, NORMAL, GOOD, EXCELLENT, MASTERWORK, LEGENDARY };
	public enum LogSource { CITY, NAMEGEN, WORLDGEN, MAIN, IMPORTANT, FACTION, FACTIONACTION, PEOPLE, EVENT, PROFILE };
	public enum LogAllowance { ALL, SOME, NONE };
	public enum EventBranchStyle { PRIORITY, ROLL };
}